version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_system
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      TAKE_FILE_OWNERSHIP: "true"
      network.host: "0.0.0.0"
      http.port: "9200"
      transport.host: localhost
      transport.tcp.port: "9300"
      xpack.ml.enabled: "false"
    # volumes:
    #   - ./.data/elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/chat_system"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elastic
    links:
      - db
      - elastic
    environment:
      DB_USER: root
      DB_NAME: chat_system
      DB_PASSWORD: password
      DB_HOST: db
      ELASTIC_HOST: "elastic"
      ELASTIC_PORT: "9200"
